### ISSUE TITLE
Selection Mode (Maybe a bunch of separate modes) 

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#101]
Implement Selection Mode. Selection mode is a general-purpose editor mode in which AEG components can be selected, moved, duplicated, and deleted.  

In selection mode, users should be able to select AEG components (Cuts (and their children) and Atoms). Once selected users should be able to drag and place components elsewhere using their mouse. They should also be able to duplicate (copy) selected items (upon which the duplicate will become the new selected item) and move these copies somewhere (paste). Alternatively, they should be able to delete selected components.  (Make a new issue for deletion)

Like atom and ellipse creation mode, selected components being dragged should not be in the graph and should be highlighted green if they can be placed at the current location, and red if they cannot. 

Open Design question(s):
1) Unlike when drawing a new cut, in which the cut can be drawn around existing elements, a component being moved should probably never be allowed to be placed over other elements. 
   * We may make an exception for a structure containing only Cuts (Since it is conceivable you may want to move a double cut to surround a new atom). (OPTIONAL)
2) It is conceivable that someone may want to delete a cut but leave the children without deleting them, should this be handled via a separate erase mode that only deletes the outermost cut? 
3) What is a good mouse-based control to indicate duplication? Should this be turned into a different mode? But surely the hotkeys for copy and paste should still work in this mode?

**Comment by RyanR712** [comment]
Closed by #151, #152, #153, all requested methods
