### ISSUE TITLE
Fix inserting something around something else 

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#106]
canInsert currently does not allow you to surround an already placed object, This forces the tree to be built from the top down. Fix this to allow for surrounding one or multiple objects and inserting them into the tree correctly. 
<img width="327" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/d736fa07-318f-44a0-a357-5e8fdaaaa9bb">
<img width="360" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/724094f5-3a14-475e-bc89-80d1d5035d1b">

**Comment by James-Oswald** [comment]
This may actually be caused by issues in overlaps/intersections functioning as overlaps rather than intersects. 
https://discord.com/channels/1143025340189523968/1143025340646707341/1161153332073730131

**Comment by James-Oswald** [comment]
May be fixed by #108 currently open under sub-issue #109

**Comment by James-Oswald** [comment]
<img width="876" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/aeb97059-31c0-4d85-9a1a-5cbb64da4621">
We're back!

**Comment by AnushaTiwari5** [comment]
Insert around fixed, new bug on drawing ellipse within existing ellipse
