### ISSUE TITLE
More points on ellipses for Collison check.

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#110]
Make collision check better by adding more points to the ellipse, large ellipses have space to fit atoms in. 
![image](https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/b99573c0-9876-4606-bc57-2d1fb36e0568)

**Comment by AnushaTiwari5** [comment]
- [ ] More points on ellipse
- [ ] Fix spelling errors
- [ ] Helper for ellipse-rect overlap
- [ ] simplify rectangle edge-edge overlap
- [ ] check setters and getters naming
- [ ] call AEGUtils overlap in AEGtree directly, no need to go into nodes
