### ISSUE TITLE
Issues with window resize and move. 

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#138]
On a 4k monitor atoms appear tiny!

![image](https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/da64d494-93ee-4ac7-a692-52640d2b63dd)

If you save a proof on a higher res monitor and load it on a lower res monitor... bad things happen. 

<img width="464" alt="image" src="https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/0307e286-29ec-4615-a1d4-604b075b070d">

**Comment by RyanR712** [comment]
Closed by #332, thank God
