### ISSUE TITLE
More Themes!

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#179]
Every developer should design a cool UI theme for the application in the `themes.css` file. Copy and paste an existing theme and play around until you have a cool theme! Add an `<option>` tag with `value="yourThemeName"` in the `id="theme-select"` `<select>` tag in `index.html`.
- [x] Anusha Theme
- [x] Dawn Theme
- [x] Ryan Theme
- [x] Subrina Theme

**Comment by RyanR712** [comment]
Don't forget to add the option tag in the about.html and aeg.html too!

**Comment by RyanR712** [comment]
As discussed in the 10/23 meeting, consider pug for generating html code and abstracting things such as theme selection
