### ISSUE TITLE
Boxpocalypse!

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#180]
Simple visual glitch, bounding boxes remain when they shouldn't.  

Steps to reproduce:
1) Enter cut mode
2) Check show guidelines
3) Begin drawing a cut (Mousedown)
4) Drag mouse outside canvas
5) Drag mouse back into canvas
6) You are now drawing a bounding box without a cut

https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/bcf77f07-4f2c-4e8a-bd45-cba8a4c6677b

**Comment by DawnTheWitch** [comment]
Why are the boxes are color coded in this

**Comment by James-Oswald** [comment]
> Why are the boxes are color coded in this

Unsure, in the take right before this they were not color coded. I did not edit the code in any way between the two takes.
