### ISSUE TITLE
Proof Mode Master Issue

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#208]
You are free to create new issues for each of these items. This issue is to track proof mode progress. 

Functionality:
- [x] Switch to proof mode: #197 
- [x] #229
- [x] #230
- [x] #228

Implement Inference Rules:
- [x] #249
- [x] Same Level Resize (Harder) (Requires draw mode resize)
- [x] #215
- [x] #221
- [x] Insertion (Hardest) 
- [x] #227
- [x] #251
- [x] #257

**Comment by James-Oswald** [comment]
Good work team

**Comment by AnushaTiwari5** [comment]
ty dawn and anusha for keeping ryans promises
