### ISSUE TITLE
Atom Swap While Mouse Down Doesn't Update Canvas

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#212]
When placing an atom, if you have the mouse down placing an atom and the atom is being displayed on the canvas, pressing a key to swap the atom type will swap the atom on the toolbar and if the mouse is released it will place the new atom type.
However, the atom displayed on the canvas will still be the old atom until the mouse is moved. 

https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/3c55e702-8ac3-4236-8062-e9646f64a2e1

Pressing the key to change the atom type should change the atom instantaneously.

**Comment by DawnTheWitch** [comment]
I'll do this and turn this into a helper function tomorrow after work
![image](https://github.com/RAIRLab/Peirce-My-Heart/assets/93628226/227781b7-f2f6-47c0-b329-004f27af83ed)

**Comment by RyanR712** [comment]
Closed by PR #243
