### ISSUE TITLE
Remove the "website" portion of the project.

### ISSUE THREAD

**Issue by James-Oswald** [RAIRLab/Peirce-My-Heart#322]
Remove the "website" portion of the project. That is: `aeg.html` and `about.html`. Keep the documentation but do not link to it. All of this information will be included in the user manual.

- [x] Remove `aeg.html` and `about.html`.
- [x] Remove the button that links to them, replace it with a clear button for draw mode.

**Comment by oranjan** [comment]
Hi , can i work on this
