### ISSUE TITLE
Ellipse bounding box

### ISSUE THREAD

**Issue by AnushaTiwari5** [RAIRLab/Peirce-My-Heart#36]
Calculate ellipse bounding box using shortest distance method.
"convert the ellipse to a polar coordinate parameterization in terms of an angle, use the center of both ellipses to get an angle to find the point on E1 closet to E2, then just run the is a point inside an ellipse check."

![image](https://github.com/RAIRLab/Peirce-My-Heart/assets/89546165/a7469ce2-fc8f-422b-80c3-00bbf0079d77)

**Comment by James-Oswald** [comment]
One way of finding that

https://www.desmos.com/calculator/oog6einpd5
