### ISSUE TITLE
[BUG] Ellipse Guidelines Are Not Correct with Offsets

### ISSUE THREAD

**Issue by RyanR712** [RAIRLab/Peirce-My-Heart#395]
**Describe the bug**
Ellipse guidelines are not correctly calculated when an offset is introduced.

**To Reproduce**
Use the drag tool to introduce an offset.

Click the "Show Guidelines" checkbox for ellipses.

Draw an ellipse. You will see that the offset is not taken into consideration.

**Expected behavior**
Ellipse guidelines should be around each ellipse, regardless of offset.

**Screenshots Or Video**

https://github.com/RAIRLab/Peirce-My-Heart/assets/101666694/c294cb30-e422-4a1c-a3aa-04ba54474264

**Comment by James-Oswald** [comment]
Interesting, I guess the bounding boxes aren't being moved by the offset, hopefully this issue is as simple as adding the offset to their positions.
