### ISSUE TITLE
The previous symbol made is stored on the canvas with new ellipses after certain steps

### ISSUE THREAD

**Issue by 10dine** [RAIRLab/Peirce-My-Heart#41]
https://github.com/RAIRLab/Peirce-My-Heart/assets/25779453/dc7c5c8a-2c07-495e-9b8c-fd2e659966e1

1. Click circle button.
2. Make circle(s).
3. Click symbol button.
4. Make symbol(s).
5. Change cut to circumscribed.
6. Click circle button.
7. Make circle(s). <-where bug appears

**Comment by 10dine** [comment]
1. Click the circle button.
2. Make circle(s).
3. Click symbol button.
4. Make symbol(s).
5. Change cut mode to circumscribed.
6. Click circle button.
7. Make circles. <-where bug appears

**Comment by DawnTheWitch** [comment]
This has been fixed along with issue #35
