### ISSUE TITLE
Atoms Disappearing

### ISSUE THREAD

**Issue by DawnTheWitch** [RAIRLab/Peirce-My-Heart#51]
Sometimes when constant clicks happen, certain atoms previously placed will suddenly disappear.
Current cause is unknown and cannot be replicated on my machine, please post any situations where this happens.

**Comment by James-Oswald** [comment]
The bug appears to delete any characters that were created using a single mouse down and mouse up with no mouse move events triggered in between them (we will refer to these as NMME Atoms) on the next move event after a mouse down. 

A minimal reproducible example:
1) Enter Atom mode by pressing the atom mode button.
2) Move mouse to center (any arbitrary position works) of canvas 
3) Press and release character selection key (such as "a" key on keyboard)
4) Create an NMME Atom by clicking and releasing the mouse button without moving the mouse. 
5) Move the mouse somewhere else
6) Hold down mouse button and move the mouse, NMME atom will disappear. 

Video:

https://github.com/RAIRLab/Peirce-My-Heart/assets/43485956/aba634f0-9f0c-47a7-b361-fb666fc3723f
